apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: front
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: 'https://github.com/matsow12/ArgoCD.git'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
